### ISSUE TITLE
This subgraph is undeployed

### ISSUE THREAD

**Issue by welps** [graphprotocol/compound-v2-subgraph#20]
Hi @juanmardefago ,

This subgraph is showing up as undeployed now on the graph hosted service. Is this intended / was this retired? https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2

![2022-08-08-224632_1497x759_scrot](https://user-images.githubusercontent.com/677680/183552497-82c4cc23-9428-49ed-9516-a177f583aa30.png)

**Comment by juanmardefago** [comment]
No idea what happened, but I'll ask around to check if this was indeed intended or an issue.

Thanks for reporting!

**Comment by welps** [comment]
Looks like it's back up. Thanks!
